# Custom Language File for Launcher Customizer

[ejs.app]
title = "짠피지 서버 시즌2"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "짠피지 시즌2에 오신걸 환영합니다"
welcomeDescription = ""
welcomeDescCTA = ""
